#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

ynh_go_install

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=1 go build -o findmydevice
popd

ynh_go_remove

chmod +x "$install_dir/findmydevice"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Server for saving location data send by fmd" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

if $allow_public_registration
then
	token=""
else
	token=$(ynh_string_random --length=8)
fi
ynh_app_setting_set --key=token --value="$token"
ynh_config_add --template="config.example.yml" --destination="$data_dir/config.yml"

#=================================================
# SET FILE OWNERSHIP / PERMISSIONS
#=================================================

myynh_set_permissions

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --wait_until="listening on" --log_path="/var/log/$app/$app.log" --timeout=900

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
